set(ipm_sources 
    highspm/CurtisReidScaling.cpp 
    highspm/FactorHiGHSSolver.cpp 
    highspm/HpmSolver.cpp
    highspm/HpmIterate.cpp 
    highspm/HpmModel.cpp)

set(ipm_headers
    highspm/CurtisReidScaling.h
    highspm/FactorHiGHSSolver.h
    highspm/HpmSolver.h
    highspm/HpmConst.h
    highspm/HpmInfo.h
    highspm/HpmIterate.h
    highspm/HpmModel.h
    highspm/HpmOption.h
    highspm/HpmStatus.h
    highspm/LinearSolver.h)

set(factor_highs_sources
    factorhighs/Analyse.cpp
    factorhighs/CallAndTimeBlas.cpp
    factorhighs/DataCollector.cpp
    factorhighs/DenseFactHybrid.cpp
    factorhighs/DenseFactKernel.cpp
    factorhighs/DgemmParallel.cpp
    factorhighs/Factorise.cpp
    factorhighs/FormatHandler.cpp
    factorhighs/HybridHybridFormatHandler.cpp
    factorhighs/HybridSolveHandler.cpp
    factorhighs/KrylovMethodsIpm.cpp
    factorhighs/Numeric.cpp
    factorhighs/SolveHandler.cpp
    factorhighs/Swaps.cpp
    factorhighs/SymScaling.cpp
    factorhighs/Symbolic.cpp)

set(factor_highs_headers
    factorhighs/Analyse.h
    factorhighs/CallAndTimeBlas.h
    factorhighs/DataCollector.h
    factorhighs/DenseFact.h
    factorhighs/DgemmParallel.h
    factorhighs/FactorHiGHS.h
    factorhighs/FactorHiGHSSettings.h
    factorhighs/Factorise.h
    factorhighs/FormatHandler.h
    factorhighs/HybridHybridFormatHandler.h
    factorhighs/HybridSolveHandler.h
    factorhighs/KrylovMethodsIpm.h
    factorhighs/Numeric.h
    factorhighs/ReturnValues.h
    factorhighs/SolveHandler.h
    factorhighs/Swaps.h
    factorhighs/SymScaling.h
    factorhighs/Symbolic.h
    factorhighs/Timing.h)

set(util_sources
    auxiliary/Auxiliary.cpp
    auxiliary/KrylovMethods.cpp
    auxiliary/HpmLog.cpp
    auxiliary/VectorOperations.cpp)

set(util_headers
    auxiliary/Auxiliary.h
    auxiliary/IntConfig.h
    auxiliary/KrylovMethods.h
    auxiliary/HpmLog.h
    auxiliary/mycblas.h
    auxiliary/VectorOperations.h)

